#
#	Makefile for the projects
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

include     .makedep

PRE_DIRS	:= $(OS)

cleanExtra:
	rm -fr MACOSX/*/build MACOSX/*/build-iphone

