#   
#   buildConfig.sh -- Build configuration file.
#   
#   WARNING: DO NOT EDIT. This file is generated by configure.
#   
#   Use "./configure --help" for available options.
#   
################################################################################
#
#   Key Product Settigns
#
BLD_APPWEB_PRODUCT=1
BLD_PRODUCT="appweb"
BLD_NAME="Embedthis Appweb"
BLD_VERSION="3.1.2"
BLD_NUMBER="1"
BLD_MAJOR_VERSION="3"
BLD_MINOR_VERSION="1"
BLD_PATCH_VERSION="2"
BLD_TYPE="RELEASE"
BLD_TUNE=MPR_TUNE_SIZE
BLD_DEFAULTS="standard"
BLD_COMPONENTS=" ar cc make nm ranlib doxygen regexp mpr matrixssl openssl ssl sqlite ejs php appweb"
BLD_EMBEDTHIS=0

#
#   Other Product Settings
#
BLD_COMPANY="Embedthis"
BLD_DEBUG=0
BLD_DIRS="build projects obj lib modules bin src test all doc samples package releases"
BLD_CLEAN_INSTALL="0"
BLD_LICENSE="gpl"
BLD_COMMERCIAL="0"

#
#   Host and Build System Settings.
#
BLD_HOST_SYSTEM="arm-s3c6410-linux"
BLD_BUILD_SYSTEM="i686-pc-linux"
BLD_CROSS="1"

#
#   Host System Settings 
#
BLD_HOST_OS="LINUX"
BLD_HOST_CPU_ARCH=MPR_CPU_ARM
BLD_HOST_CPU="arm"
BLD_HOST_CPU_UPPER="ARM"
BLD_HOST_CPU_MODEL=""
BLD_HOST_DIST="Unknown"
BLD_HOST_DIST_VER="Unknown"
BLD_HOST_UNIX=1
BLD_HOST_WIN=0

#
#   Build System Settings for Build Tools
#
BLD_BUILD_OS="LINUX"
BLD_BUILD_CPU_ARCH=MPR_CPU_IX86
BLD_BUILD_CPU="i686"
BLD_BUILD_CPU_UPPER="I686"
BLD_BUILD_CPU_MODEL="i686"
BLD_BUILD_UNIX=1
BLD_BUILD_WIN=0

#
#   System and Installation Directories
#
BLD_ROOT_PREFIX="/"
BLD_PREFIX="/usr/appWeb"
BLD_BIN_PREFIX="/usr/appWeb/local/bin"
BLD_CFG_PREFIX="/etc/appweb"
BLD_DOC_PREFIX="/usr/appWeb/share/doc/appweb"
BLD_INC_PREFIX="/usr/appWeb/include/appweb"
BLD_LIB_PREFIX="/usr/appWeb/lib/appweb"
BLD_LOG_PREFIX="/var/log/appweb"
BLD_MAN_PREFIX="/usr/appWeb/share/man"
BLD_MOD_PREFIX="/usr/appWeb/lib/appweb/modules"
BLD_SAM_PREFIX="/usr/appWeb/share/appweb/samples"
BLD_SRC_PREFIX="/usr/appWeb/src/appweb-3.1.2"
BLD_WEB_PREFIX="/var/web"

#
#   Directories for native building
#
BLD_BIN_NAME="bin/arm-s3c6410-linux"
BLD_LIB_NAME="lib/arm-s3c6410-linux"
BLD_OBJ_NAME="obj/arm-s3c6410-linux"
BLD_MOD_NAME="modules/arm-s3c6410-linux"
BLD_INC_NAME="src/include"

#
#   Standard Feature Selection
#
BLD_FEATURE_ASSERT=1
BLD_FEATURE_CMD=1
BLD_FEATURE_COMPLETE_NATIVE=1
BLD_FEATURE_COMPLETE_CROSS=0
BLD_FEATURE_DOC=1
BLD_FEATURE_DEVICE=
BLD_FEATURE_FLOATING_POINT=1
BLD_FEATURE_LEGACY_API=0
BLD_FEATURE_MULTITHREAD=0
BLD_FEATURE_NUM_TYPE=double
BLD_FEATURE_POLL=1
BLD_FEATURE_SAMPLES=0
BLD_FEATURE_TEST=0
BLD_FEATURE_VMALLOC=1
BLD_FEATURE_STATIC=1

#
#   Extended Feature Selection
#
BLD_FEATURE_ACCESS_LOG=1
BLD_FEATURE_ANGEL=1
BLD_FEATURE_AUTH_DIGEST=1
BLD_FEATURE_AUTH=1
BLD_FEATURE_AUTH_FILE=1
BLD_FEATURE_AUTH_PAM=0
BLD_FEATURE_CGI=1
BLD_FEATURE_CHUNK=1
BLD_FEATURE_DIR=1
BLD_FEATURE_EJS_ALL_IN_ONE=1
BLD_FEATURE_EJS_AUTO_COMPILE=1
BLD_FEATURE_EJS_CROSS_COMPILER=1
BLD_FEATURE_EJS_DB=1
BLD_FEATURE_EJS_DOC=0
BLD_FEATURE_EJS_E4X=1
BLD_FEATURE_EJS_LANG=EJS_LANG_FIXED
BLD_FEATURE_EJS_WEB=1
BLD_FEATURE_EGI=1
BLD_FEATURE_CONFIG=template/standard
BLD_FEATURE_CONFIG_PARSE=1
BLD_FEATURE_FILE=1
BLD_FEATURE_HTTP=1
BLD_FEATURE_HTTP_CLIENT=1
BLD_FEATURE_LOG=1
BLD_FEATURE_NET=1
BLD_FEATURE_NUM_TYPE_DOUBLE=1
BLD_FEATURE_RANGE=1
BLD_FEATURE_RUN_AS_SERVICE=1
BLD_FEATURE_SEND=1
BLD_FEATURE_UPLOAD=1
BLD_FEATURE_XML=1

BLD_HTTP_PORT=80
BLD_SSL_PORT=4443


#
#   File extensions 
#
BLD_BUILD_ARCH=".a"
BLD_BUILD_EXE=""
BLD_BUILD_OBJ=".o"
BLD_BUILD_PIOBJ=".o"
BLD_BUILD_CLASS=".class"
BLD_BUILD_SHLIB=".so"
BLD_BUILD_SHOBJ=".so"
BLD_HOST_ARCH=".a"
BLD_HOST_EXE=""
BLD_HOST_OBJ=".o"
BLD_HOST_PIOBJ=".o"
BLD_HOST_CLASS=".class"
BLD_HOST_SHLIB=".so"
BLD_HOST_SHOBJ=".so"
#
#   Select Native or cross development flags
#
: ${BUILD_NATIVE:=1}
: ${BUILD_CROSS:=1}
if [ "${BUILDING_CROSS}" != 1 ] ; then

	#
	#	Configuration for Native Compilation on the Build System
	#
	BUILD_NATIVE_OR_COMPLETE_CROSS=1
	BUILD_CROSS_OR_COMPLETE_NATIVE=1

	#
	#   O/S and CPU settings
	#
	LINUX=1
	BLD_OS="LINUX"
	BLD_CPU_ARCH=MPR_CPU_IX86
	BLD_CPU="i686"
	BLD_CPU_UPPER="I686"
	BLD_CPU_MODEL="i686"
	BLD_DIST="ubuntu"
	BLD_DIST_VER="8.10"
	BLD_UNIX_LIKE=1
	BLD_WIN_LIKE=0

	#
	#   Compiler and linker flags
	#
	BLD_CFLAGS=""
	BLD_DFLAGS=""
	BLD_IFLAGS=""
	BLD_LDFLAGS=""
	BLD_JFLAGS=""
	BLD_CPPFLAGS=""

	#
	#   File extensions
	#
	BLD_ARCH=".a"
	BLD_EXE=""
	BLD_CLASS=".class"
	BLD_SHLIB=".so"
	BLD_SHOBJ=".so"
	BLD_LIB=".a"
	BLD_OBJ=".o"
	BLD_PIOBJ=".o"

	#
	#   Output directories 
	#
	BLD_TOOLS_DIR="${BLD_TOP}/build/bin"
	BLD_BIN_DIR=${BLD_TOP}/bin
	BLD_OBJ_DIR=${BLD_TOP}/obj
	BLD_MOD_DIR=${BLD_TOP}/modules
	BLD_LIB_DIR=${BLD_TOP}/lib
	BLD_INC_DIR=${BLD_TOP}/src/include
	BLD_ABS_BIN_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/bin"
	BLD_ABS_LIB_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/lib"
	BLD_ABS_OBJ_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/obj"
	BLD_ABS_MOD_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/modules"
	BLD_ABS_INC_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/src/include"

	#
	#   Native Compilation Features
	#
    BLD_FEATURE_ROMFS=0

	#
	#   Setup environment variables
	#
	export PATH="${PATH}:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/bin:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/lib:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/lib:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/build/bin:/sbin:/usr/sbin::"

	#
	#   AR
	#
	BLD_FEATURE_AR=1
	BLD_AR="/usr/bin/ar"
	BLD_AR_BUILTIN=0
	BLD_AR_WITH="1"

	#
	#   CC
	#
	BLD_FEATURE_CC=1
	BLD_CC="/usr/bin/cc"
	BLD_CC_BUILTIN=0
	BLD_CC_WITH="1"
	BLD_CC_CYGWIN=0
	BLD_CC_DIAB=0
	BLD_CC_DYN_LOAD=1
	BLD_CC_MTUNE=1
	BLD_CC_MMU=1
	BLD_CC_STACK_PROTECTOR=1

	#
	#   MAKE
	#
	BLD_FEATURE_MAKE=1
	BLD_MAKE="/usr/bin/make"
	BLD_MAKE_BUILTIN=0
	BLD_MAKE_WITH="1"

	#
	#   NM
	#
	BLD_FEATURE_NM=1
	BLD_NM="/usr/bin/nm"
	BLD_NM_BUILTIN=0
	BLD_NM_WITH="1"

	#
	#   RANLIB
	#
	BLD_FEATURE_RANLIB=1
	BLD_RANLIB="/usr/bin/ranlib"
	BLD_RANLIB_BUILTIN=0
	BLD_RANLIB_WITH="1"

	#
	#   DOXYGEN
	#
	BLD_FEATURE_DOXYGEN=0

	#
	#   REGEXP
	#
	BLD_FEATURE_REGEXP=1
	BLD_REGEXP="src/regexp"
	BLD_REGEXP_BUILTIN=1
	BLD_REGEXP_LIBS="pcre"
	BLD_REGEXP_WITH="1"

	#
	#   MPR
	#
	BLD_FEATURE_MPR=1
	BLD_MPR="src/mpr"
	BLD_MPR_BUILTIN=1
	BLD_MPR_LIBS="mpr pcre"
	BLD_MPR_OPTIONAL_DEPENDENCIES="regexp"
	BLD_MPR_WITH="1"

	#
	#   MATRIXSSL
	#
	BLD_FEATURE_MATRIXSSL=0

	#
	#   OPENSSL
	#
	BLD_FEATURE_OPENSSL=0

	#
	#   SSL
	#
	BLD_FEATURE_SSL=0

	#
	#   SQLITE
	#
	BLD_FEATURE_SQLITE=1
	BLD_SQLITE="src/db/sqlite"
	BLD_SQLITE_BUILTIN=1
	BLD_SQLITE_DEPENDENCIES="mpr"
	BLD_SQLITE_LIBS="sqlite3 mpr pcre"
	BLD_SQLITE_WITH="1"

	#
	#   EJS
	#
	BLD_FEATURE_EJS=1
	BLD_EJS="src/ejs"
	BLD_EJS_BUILTIN=1
	BLD_EJS_DEPENDENCIES="mpr"
	BLD_EJS_LIBS="ajs sqlite3 mpr pcre mpr pcre"
	BLD_EJS_OPTIONAL_DEPENDENCIES="ssl sqlite"
	BLD_EJS_WITH="1"

	#
	#   PHP
	#
	BLD_FEATURE_PHP=0

	#
	#   APPWEB
	#
	BLD_FEATURE_APPWEB=1
	BLD_APPWEB="src/appweb"
	BLD_APPWEB_BUILTIN=1
	BLD_APPWEB_DEPENDENCIES="mpr"
	BLD_APPWEB_LIBS="appweb ejs ajs sqlite3 mpr pcre mpr pcre mpr pcre"
	BLD_APPWEB_OPTIONAL_DEPENDENCIES="ssl ejs"
	BLD_APPWEB_WITH="1"



else

	#
	#	Configuration for Cross-Compilation for the Target
	#
	BUILD_NATIVE_OR_COMPLETE_CROSS=1
	BUILD_CROSS_OR_COMPLETE_NATIVE=1

	#
	#   O/S and CPU settings
	#
	LINUX=1
	BLD_OS="LINUX"
	BLD_CPU_ARCH=MPR_CPU_ARM
	BLD_CPU="arm"
	BLD_CPU_UPPER="ARM"
	BLD_CPU_MODEL=""
	BLD_DIST="Unknown"
	BLD_DIST_VER="Unknown"
	BLD_UNIX_LIKE=1
	BLD_WIN_LIKE=0

	#
	#   Compiler and linker flags
	#
	BLD_CFLAGS=""
	BLD_DFLAGS=""
	BLD_IFLAGS=""
	BLD_LDFLAGS=""
	BLD_JFLAGS=""
	BLD_CPPFLAGS=""

	#
	#   File extensions
	#
	BLD_ARCH=".a"
	BLD_EXE=""
	BLD_CLASS=".class"
	BLD_SHLIB=".so"
	BLD_SHOBJ=".so"
	BLD_LIB=".a"
	BLD_OBJ=".o"
	BLD_PIOBJ=".o"

	#
	#   Output directories 
	#
	BLD_TOOLS_DIR="${BLD_TOP}/build/bin"
	BLD_BIN_DIR=${BLD_TOP}/bin/arm-s3c6410-linux
	BLD_OBJ_DIR=${BLD_TOP}/obj/arm-s3c6410-linux
	BLD_MOD_DIR=${BLD_TOP}/modules/arm-s3c6410-linux
	BLD_LIB_DIR=${BLD_TOP}/lib/arm-s3c6410-linux
	BLD_INC_DIR=${BLD_TOP}/src/include
	BLD_ABS_BIN_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/bin/arm-s3c6410-linux"
	BLD_ABS_LIB_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/lib/arm-s3c6410-linux"
	BLD_ABS_OBJ_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/obj/arm-s3c6410-linux"
	BLD_ABS_MOD_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/modules/arm-s3c6410-linux"
	BLD_ABS_INC_DIR="/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/src/include"

	#
	#   Cross Compilation Features
	#
    BLD_FEATURE_ROMFS=0

	#
	#   Setup environment variables
	#
	export PATH="${PATH}:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/bin:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/lib:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/lib:/home/bhsong/develop/svn/ldd6410/utils/appweb-3.1.2/build/bin:/sbin:/usr/sbin::"

	#
	#   AR
	#
	BLD_FEATURE_AR=1
	BLD_AR="/usr/local/arm/4.2.2-eabi/usr/bin/arm-linux-ar"
	BLD_AR_BUILTIN=0
	BLD_AR_WITH="1"

	#
	#   CC
	#
	BLD_FEATURE_CC=1
	BLD_CC="/usr/local/arm/4.2.2-eabi/usr/bin/arm-linux-gcc"
	BLD_CC_BUILTIN=0
	BLD_CC_WITH="1"
	BLD_CC_CYGWIN=0
	BLD_CC_DIAB=0
	BLD_CC_DYN_LOAD=1
	BLD_CC_MTUNE=0
	BLD_CC_MMU=1
	BLD_CC_STACK_PROTECTOR=1

	#
	#   MAKE
	#
	BLD_FEATURE_MAKE=1
	BLD_MAKE="/usr/bin/make"
	BLD_MAKE_BUILTIN=0
	BLD_MAKE_WITH="1"

	#
	#   NM
	#
	BLD_FEATURE_NM=1
	BLD_NM="/usr/bin/nm"
	BLD_NM_BUILTIN=0
	BLD_NM_WITH="1"

	#
	#   RANLIB
	#
	BLD_FEATURE_RANLIB=1
	BLD_RANLIB="/usr/local/arm/4.2.2-eabi/usr/bin/arm-linux-ranlib"
	BLD_RANLIB_BUILTIN=0
	BLD_RANLIB_WITH="1"

	#
	#   DOXYGEN
	#
	BLD_FEATURE_DOXYGEN=0

	#
	#   REGEXP
	#
	BLD_FEATURE_REGEXP=1
	BLD_REGEXP="src/regexp"
	BLD_REGEXP_BUILTIN=1
	BLD_REGEXP_LIBS="pcre"
	BLD_REGEXP_WITH="1"

	#
	#   MPR
	#
	BLD_FEATURE_MPR=1
	BLD_MPR="src/mpr"
	BLD_MPR_BUILTIN=1
	BLD_MPR_LIBS="mpr pcre"
	BLD_MPR_OPTIONAL_DEPENDENCIES="regexp"
	BLD_MPR_WITH="1"

	#
	#   MATRIXSSL
	#
	BLD_FEATURE_MATRIXSSL=0

	#
	#   OPENSSL
	#
	BLD_FEATURE_OPENSSL=0

	#
	#   SSL
	#
	BLD_FEATURE_SSL=0

	#
	#   SQLITE
	#
	BLD_FEATURE_SQLITE=1
	BLD_SQLITE="src/db/sqlite"
	BLD_SQLITE_BUILTIN=1
	BLD_SQLITE_DEPENDENCIES="mpr"
	BLD_SQLITE_LIBS="sqlite3 mpr pcre"
	BLD_SQLITE_WITH="1"

	#
	#   EJS
	#
	BLD_FEATURE_EJS=1
	BLD_EJS="src/ejs"
	BLD_EJS_BUILTIN=1
	BLD_EJS_DEPENDENCIES="mpr"
	BLD_EJS_LIBS="ajs sqlite3 mpr pcre mpr pcre"
	BLD_EJS_OPTIONAL_DEPENDENCIES="ssl sqlite"
	BLD_EJS_WITH="1"

	#
	#   PHP
	#
	BLD_FEATURE_PHP=0

	#
	#   APPWEB
	#
	BLD_FEATURE_APPWEB=1
	BLD_APPWEB="src/appweb"
	BLD_APPWEB_BUILTIN=1
	BLD_APPWEB_DEPENDENCIES="mpr"
	BLD_APPWEB_LIBS="appweb ejs ajs sqlite3 mpr pcre mpr pcre mpr pcre"
	BLD_APPWEB_OPTIONAL_DEPENDENCIES="ssl ejs"
	BLD_APPWEB_WITH="1"


fi

if [ "${EXPORT_OBJECTS}" = 0 ] ; then
  BLD_OBJ_DIR=.
fi

#
#   Patch the !!BLD_XXX!! 
#
patchFile() {
    local file arg

    [ $# -lt 1 ] && echo "Bad args: patchFile $*" && exit 255

    arg=1
    while [ $arg -le $# ] ; do
        file=${!arg}
        if [ -s "${file}" ] ; then
            cp "${file}" /tmp/patch$$ 
            sed -e "
s^!!BLD_BIN_PREFIX!!^${BLD_BIN_PREFIX}^g;
s^!!BLD_CFG_PREFIX!!^${BLD_CFG_PREFIX}^g;
s^!!BLD_COMPANY!!^${BLD_COMPANY}^g;
s^!!BLD_DATE!!^${BLD_DATE}^g;
s^!!BLD_DOC_PREFIX!!^${BLD_DOC_PREFIX}^g;
s^!!BLD_HOST_CPU!!^${BLD_HOST_CPU}^g;
s^!!BLD_HOST_CPU_MAPPED!!^${BLD_HOST_CPU_MAPPED}^g;
s^!!BLD_HOST_DIST!!^${BLD_HOST_DIST}^g;
s^!!BLD_HOST_OS!!^${BLD_HOST_OS}^g;
s^!!BLD_INC_PREFIX!!^${BLD_INC_PREFIX}^g;
s^!!BLD_LIB_PREFIX!!^${BLD_LIB_PREFIX}^g;
s^!!BLD_LOG_PREFIX!!^${BLD_LOG_PREFIX}^g;
s^!!BLD_MAN_PREFIX!!^${BLD_MAN_PREFIX}^g;
s^!!BLD_MOD_PREFIX!!^${BLD_MOD_PREFIX}^g;
s^!!BLD_NAME!!^${BLD_NAME}^g;
s^!!BLD_NUMBER!!^${BLD_NUMBER}^g;
s^!!BLD_OSVER!!^${BLD_OSVER}^g;
s^!!BLD_PREFIX!!^${BLD_PREFIX}^g;
s^!!BLD_PRODUCT!!^${BLD_PRODUCT}^g;
s^!!BLD_SAM_PREFIX!!^${BLD_SAM_PREFIX}^g;
s^!!BLD_SBIN_PREFIX!!^${BLD_SBIN_PREFIX}^g;
s^!!BLD_SRC_PREFIX!!^${BLD_SRC_PREFIX}^g;
s^!!BLD_TYPE!!^${BLD_TYPE}^g;
s^!!BLD_VERSION!!^${BLD_VERSION}^g;
s^!!BLD_WEB_PREFIX!!^${BLD_WEB_PREFIX}^g;
s^!!ORIG_BLD_BIN_PREFIX!!^${ORIG_BLD_BIN_PREFIX}^g;
s^!!ORIG_BLD_CFG_PREFIX!!^${ORIG_BLD_CFG_PREFIX}^g;
s^!!ORIG_BLD_DOC_PREFIX!!^${ORIG_BLD_DOC_PREFIX}^g;
s^!!ORIG_BLD_INC_PREFIX!!^${ORIG_BLD_INC_PREFIX}^g;
s^!!ORIG_BLD_LIB_PREFIX!!^${ORIG_BLD_LIB_PREFIX}^g;
s^!!ORIG_BLD_LOG_PREFIX!!^${ORIG_BLD_LOG_PREFIX}^g;
s^!!ORIG_BLD_MAN_PREFIX!!^${ORIG_BLD_MAN_PREFIX}^g;
s^!!ORIG_BLD_MOD_PREFIX!!^${ORIG_BLD_MOD_PREFIX}^g;
s^!!ORIG_BLD_PREFIX!!^${ORIG_BLD_PREFIX}^g;
s^!!ORIG_BLD_SAM_PREFIX!!^${ORIG_BLD_SAM_PREFIX}^g;
s^!!ORIG_BLD_SBIN_PREFIX!!^${ORIG_BLD_SBIN_PREFIX}^g;
s^!!ORIG_BLD_SRC_PREFIX!!^${ORIG_BLD_SRC_PREFIX}^g;
s^!!ORIG_BLD_WEB_PREFIX!!^${ORIG_BLD_WEB_PREFIX}^g;
s^!!ROOT_DIR!!^${ROOT_DIR}^g;
s^!!BLD_ABS_BIN_DIR!!^${BLD_ABS_BIN_DIR}^g;
s^!!BLD_ABS_INC_DIR!!^${BLD_ABS_INC_DIR}^g;
s^!!BLD_ABS_LIB_DIR!!^${BLD_ABS_LIB_DIR}^g;
s^!!BLD_ABS_MOD_DIR!!^${BLD_ABS_MOD_DIR}^g;
s^!!BLD_ABS_OBJ_DIR!!^${BLD_ABS_OBJ_DIR}^g;
s^!!BLD_APPWEB!!^${BLD_APPWEB}^g;
s^!!BLD_APPWEB_BUILTIN!!^${BLD_APPWEB_BUILTIN}^g;
s^!!BLD_APPWEB_DEPENDENCIES!!^${BLD_APPWEB_DEPENDENCIES}^g;
s^!!BLD_APPWEB_LIBS!!^${BLD_APPWEB_LIBS}^g;
s^!!BLD_APPWEB_OPTIONAL_DEPENDENCIES!!^${BLD_APPWEB_OPTIONAL_DEPENDENCIES}^g;
s^!!BLD_APPWEB_WITH!!^${BLD_APPWEB_WITH}^g;
s^!!BLD_AR!!^${BLD_AR}^g;
s^!!BLD_ARCH!!^${BLD_ARCH}^g;
s^!!BLD_AR_BUILTIN!!^${BLD_AR_BUILTIN}^g;
s^!!BLD_AR_WITH!!^${BLD_AR_WITH}^g;
s^!!BLD_BIN_DIR!!^${BLD_BIN_DIR}^g;
s^!!BLD_BIN_NAME!!^${BLD_BIN_NAME}^g;
s^!!BLD_BUILD_ARCH!!^${BLD_BUILD_ARCH}^g;
s^!!BLD_BUILD_CLASS!!^${BLD_BUILD_CLASS}^g;
s^!!BLD_BUILD_CPU!!^${BLD_BUILD_CPU}^g;
s^!!BLD_BUILD_CPU_ARCH!!^${BLD_BUILD_CPU_ARCH}^g;
s^!!BLD_BUILD_CPU_MODEL!!^${BLD_BUILD_CPU_MODEL}^g;
s^!!BLD_BUILD_CPU_UPPER!!^${BLD_BUILD_CPU_UPPER}^g;
s^!!BLD_BUILD_EXE!!^${BLD_BUILD_EXE}^g;
s^!!BLD_BUILD_OBJ!!^${BLD_BUILD_OBJ}^g;
s^!!BLD_BUILD_OS!!^${BLD_BUILD_OS}^g;
s^!!BLD_BUILD_PIOBJ!!^${BLD_BUILD_PIOBJ}^g;
s^!!BLD_BUILD_SHLIB!!^${BLD_BUILD_SHLIB}^g;
s^!!BLD_BUILD_SHOBJ!!^${BLD_BUILD_SHOBJ}^g;
s^!!BLD_BUILD_SYSTEM!!^${BLD_BUILD_SYSTEM}^g;
s^!!BLD_BUILD_UNIX!!^${BLD_BUILD_UNIX}^g;
s^!!BLD_BUILD_WIN!!^${BLD_BUILD_WIN}^g;
s^!!BLD_CC!!^${BLD_CC}^g;
s^!!BLD_CC_BUILTIN!!^${BLD_CC_BUILTIN}^g;
s^!!BLD_CC_DYN_LOAD!!^${BLD_CC_DYN_LOAD}^g;
s^!!BLD_CC_MTUNE!!^${BLD_CC_MTUNE}^g;
s^!!BLD_CC_STACK_PROTECTOR!!^${BLD_CC_STACK_PROTECTOR}^g;
s^!!BLD_CC_MMU!!^${BLD_CC_MMU}^g;
s^!!BLD_CC_WITH!!^${BLD_CC_WITH}^g;
s^!!BLD_CC_CYGWIN!!^${BLD_CC_CYGWIN}^g;
s^!!BLD_CC_DIAB!!^${BLD_CC_DIAB}^g;
s^!!BLD_CFLAGS!!^${BLD_CFLAGS}^g;
s^!!BLD_CLASS!!^${BLD_CLASS}^g;
s^!!BLD_CLEAN_INSTALL!!^${BLD_CLEAN_INSTALL}^g;
s^!!BLD_COMMERCIAL!!^${BLD_COMMERCIAL}^g;
s^!!BLD_COMPANY!!^${BLD_COMPANY}^g;
s^!!BLD_COMPONENTS!!^${BLD_COMPONENTS}^g;
s^!!BLD_CPU!!^${BLD_CPU}^g;
s^!!BLD_CPU_ARCH!!^${BLD_CPU_ARCH}^g;
s^!!BLD_CPU_MODEL!!^${BLD_CPU_MODEL}^g;
s^!!BLD_CPU_UPPER!!^${BLD_CPU_UPPER}^g;
s^!!BLD_CROSS!!^${BLD_CROSS}^g;
s^!!BLD_DEBUG!!^${BLD_DEBUG}^g;
s^!!BLD_DEFAULTS!!^${BLD_DEFAULTS}^g;
s^!!BLD_DFLAGS!!^${BLD_DFLAGS}^g;
s^!!BLD_DIRS!!^${BLD_DIRS}^g;
s^!!BLD_DIST!!^${BLD_DIST}^g;
s^!!BLD_DIST_VER!!^${BLD_DIST_VER}^g;
s^!!BLD_EXE!!^${BLD_EXE}^g;
s^!!BLD_FEATURE_ANGEL!!^${BLD_FEATURE_ANGEL}^g;
s^!!BLD_FEATURE_APACHE!!^${BLD_FEATURE_APACHE}^g;
s^!!BLD_FEATURE_APPWEB!!^${BLD_FEATURE_APPWEB}^g;
s^!!BLD_FEATURE_AR!!^${BLD_FEATURE_AR}^g;
s^!!BLD_FEATURE_ASSERT!!^${BLD_FEATURE_ASSERT}^g;
s^!!BLD_FEATURE_CC!!^${BLD_FEATURE_CC}^g;
s^!!BLD_FEATURE_CMD!!^${BLD_FEATURE_CMD}^g;
s^!!BLD_FEATURE_COMPLETE_CROSS!!^${BLD_FEATURE_COMPLETE_CROSS}^g;
s^!!BLD_FEATURE_COMPLETE_NATIVE!!^${BLD_FEATURE_COMPLETE_NATIVE}^g;
s^!!BLD_FEATURE_CONFIG_PARSE!!^${BLD_FEATURE_CONFIG_PARSE}^g;
s^!!BLD_FEATURE_DEVICE!!^${BLD_FEATURE_DEVICE}^g;
s^!!BLD_FEATURE_DOC!!^${BLD_FEATURE_DOC}^g;
s^!!BLD_FEATURE_DOXYGEN!!^${BLD_FEATURE_DOXYGEN}^g;
s^!!BLD_FEATURE_EJS!!^${BLD_FEATURE_EJS}^g;
s^!!BLD_FEATURE_EJS_DB!!^${BLD_FEATURE_EJS_DB}^g;
s^!!BLD_FEATURE_EJS_DOC!!^${BLD_FEATURE_EJS_DOC}^g;
s^!!BLD_FEATURE_EJS_E4X!!^${BLD_FEATURE_EJS_E4X}^g;
s^!!BLD_FEATURE_EJS_LANG!!^${BLD_FEATURE_EJS_LANG}^g;
s^!!BLD_FEATURE_EJS_WEB!!^${BLD_FEATURE_EJS_WEB}^g;
s^!!BLD_FEATURE_FLOATING_POINT!!^${BLD_FEATURE_FLOATING_POINT}^g;
s^!!BLD_FEATURE_HTTP!!^${BLD_FEATURE_HTTP}^g;
s^!!BLD_FEATURE_HTTP_CLIENT!!^${BLD_FEATURE_HTTP_CLIENT}^g;
s^!!BLD_FEATURE_JAVA_VM!!^${BLD_FEATURE_JAVA_VM}^g;
s^!!BLD_FEATURE_LEGACY_API!!^${BLD_FEATURE_LEGACY_API}^g;
s^!!BLD_FEATURE_MAKE!!^${BLD_FEATURE_MAKE}^g;
s^!!BLD_FEATURE_MATRIXSSL!!^${BLD_FEATURE_MATRIXSSL}^g;
s^!!BLD_FEATURE_MULTITHREAD!!^${BLD_FEATURE_MULTITHREAD}^g;
s^!!BLD_FEATURE_NUM_TYPE!!^${BLD_FEATURE_NUM_TYPE}^g;
s^!!BLD_FEATURE_OPENSSL!!^${BLD_FEATURE_OPENSSL}^g;
s^!!BLD_FEATURE_POLL!!^${BLD_FEATURE_POLL}^g;
s^!!BLD_FEATURE_RANLIB!!^${BLD_FEATURE_RANLIB}^g;
s^!!BLD_FEATURE_REGEXP!!^${BLD_FEATURE_REGEXP}^g;
s^!!BLD_FEATURE_SAMPLES!!^${BLD_FEATURE_SAMPLES}^g;
s^!!BLD_FEATURE_SERVICES!!^${BLD_FEATURE_SERVICES}^g;
s^!!BLD_FEATURE_SQLITE!!^${BLD_FEATURE_SQLITE}^g;
s^!!BLD_FEATURE_SSL!!^${BLD_FEATURE_SSL}^g;
s^!!BLD_FEATURE_STATIC!!^${BLD_FEATURE_STATIC}^g;
s^!!BLD_FEATURE_TEST!!^${BLD_FEATURE_TEST}^g;
s^!!BLD_FEATURE_VMALLOC!!^${BLD_FEATURE_VMALLOC}^g;
s^!!BLD_FEATURE_XML!!^${BLD_FEATURE_XML}^g;
s^!!BLD_HOST_CPU!!^${BLD_HOST_CPU}^g;
s^!!BLD_HOST_CPU_ARCH!!^${BLD_HOST_CPU_ARCH}^g;
s^!!BLD_HOST_CPU_MODEL!!^${BLD_HOST_CPU_MODEL}^g;
s^!!BLD_HOST_CPU_UPPER!!^${BLD_HOST_CPU_UPPER}^g;
s^!!BLD_HOST_DIST!!^${BLD_HOST_DIST}^g;
s^!!BLD_HOST_DIST_VER!!^${BLD_HOST_DIST_VER}^g;
s^!!BLD_HOST_OS!!^${BLD_HOST_OS}^g;
s^!!BLD_HOST_SYSTEM!!^${BLD_HOST_SYSTEM}^g;
s^!!BLD_HOST_UNIX!!^${BLD_HOST_UNIX}^g;
s^!!BLD_HOST_WIN!!^${BLD_HOST_WIN}^g;
s^!!BLD_IFLAGS!!^${BLD_IFLAGS}^g;
s^!!BLD_INC_DIR!!^${BLD_INC_DIR}^g;
s^!!BLD_INC_NAME!!^${BLD_INC_NAME}^g;
s^!!BLD_JFLAGS!!^${BLD_JFLAGS}^g;
s^!!BLD_LDFLAGS!!^${BLD_LDFLAGS}^g;
s^!!BLD_LIB!!^${BLD_LIB}^g;
s^!!BLD_LIB_DIR!!^${BLD_LIB_DIR}^g;
s^!!BLD_LIB_NAME!!^${BLD_LIB_NAME}^g;
s^!!BLD_LICENSE!!^${BLD_LICENSE}^g;
s^!!BLD_MAKE!!^${BLD_MAKE}^g;
s^!!BLD_MAKE_BUILTIN!!^${BLD_MAKE_BUILTIN}^g;
s^!!BLD_MAKE_WITH!!^${BLD_MAKE_WITH}^g;
s^!!BLD_MOD_DIR!!^${BLD_MOD_DIR}^g;
s^!!BLD_MOD_NAME!!^${BLD_MOD_NAME}^g;
s^!!BLD_NAME!!^${BLD_NAME}^g;
s^!!BLD_NUMBER!!^${BLD_NUMBER}^g;
s^!!BLD_OBJ!!^${BLD_OBJ}^g;
s^!!BLD_OBJ_DIR!!^${BLD_OBJ_DIR}^g;
s^!!BLD_OBJ_NAME!!^${BLD_OBJ_NAME}^g;
s^!!BLD_OS!!^${BLD_OS}^g;
s^!!BLD_PIOBJ!!^${BLD_PIOBJ}^g;
s^!!BLD_PRODUCT!!^${BLD_PRODUCT}^g;
s^!!BLD_RANLIB!!^${BLD_RANLIB}^g;
s^!!BLD_RANLIB_BUILTIN!!^${BLD_RANLIB_BUILTIN}^g;
s^!!BLD_RANLIB_WITH!!^${BLD_RANLIB_WITH}^g;
s^!!BLD_SHLIB!!^${BLD_SHLIB}^g;
s^!!BLD_SHOBJ!!^${BLD_SHOBJ}^g;
s^!!BLD_TOOLS_DIR!!^${BLD_TOOLS_DIR}^g;
s^!!BLD_TUNE!!^${BLD_TUNE}^g;
s^!!BLD_TYPE!!^${BLD_TYPE}^g;
s^!!BLD_UNIX_LIKE!!^${BLD_UNIX_LIKE}^g;
s^!!BLD_VERSION!!^${BLD_VERSION}^g;
s^!!BLD_WIN_LIKE!!^${BLD_WIN_LIKE}^g;
s^!!BUILD_CROSS_OR_COMPLETE_NATIVE!!^${BUILD_CROSS_OR_COMPLETE_NATIVE}^g;
s^!!BUILD_NATIVE_OR_COMPLETE_CROSS!!^${BUILD_NATIVE_OR_COMPLETE_CROSS}^g;
            " < /tmp/patch$$ > "${file}"
            rm -f /tmp/patch$$ 
        fi
        arg=$((arg + 1))
    done
}
